name: wf-ci-release
on:
  pull_request:
    branches:
      - release/**
    types:
      - opened
      - synchronize
jobs:
  ci-release-job:
    runs-on: ubunutu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: "${{github.ref}}"
      - name: Lint HTML with HTMLHint
        run: npx htmlhint "**/*.html"
      - name: Lint CSS With Stylelint
        run: npx stylelint "**/*.css"